# Generated by Django 3.1.6 on 2021-05-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_auto_20210515_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='acnonac',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
